# Generated by Django 4.2.7 on 2024-01-05 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
