# Generated by Django 4.2.7 on 2024-01-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0004_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
            ],
        ),
    ]
