# Generated by Django 4.2.7 on 2024-01-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
